# Generated by Django 5.0.3 on 2024-04-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client1',
            name='data_register',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order1',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product1',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
