# Generated by Django 5.0.3 on 2024-04-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_orderproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product1',
            name='image_product',
            field=models.ImageField(default='изображение', upload_to=''),
        ),
    ]
